Fix for LoL installation.

diff --git a/opt/regataos-gcs/scripts/install/pt-br/install-game-gcs/prepare-compatibility-mode b/opt/regataos-gcs/scripts/install/pt-br/install-game-gcs/prepare-compatibility-mode
--- a/opt/regataos-gcs/scripts/install/pt-br/install-game-gcs/prepare-compatibility-mode
+++ b/opt/regataos-gcs/scripts/install/pt-br/install-game-gcs/prepare-compatibility-mode
@@ -16,18 +16,18 @@ function enable_dxvk_vkd3d() {
 }
 
 function prepareCustomCompatMode() {
-	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
+	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode/drive_c"; then
 		# We're finished!
 		exit 0
 
 	else
 		# Configuring compatibility mode
-		echo "installing" > $progressbar_dir/progress-movement
-		echo "" > $progressbar_dir/progress
-		echo $app_name > $progressbar_dir/app-name
-		echo $conf_prefix_status > $progressbar_dir/status
+		echo "installing" >$progressbar_dir/progress-movement
+		echo "" >$progressbar_dir/progress
+		echo $app_name >$progressbar_dir/app-name
+		echo $conf_prefix_status >$progressbar_dir/status
 		sleep 1
-		echo "show progress bar" > $progressbar_dir/progressbar
+		echo "show progress bar" >$progressbar_dir/progressbar
 
 		export WINEPREFIX="$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
 
@@ -46,26 +46,26 @@ function prepareCustomCompatMode() {
 		alias winecfg="$CUSTOM_WINE_DIR/bin/winecfg"
 		alias msiexec="$CUSTOM_WINE_DIR/bin/msiexec"
 
-		winetricks prefix=$game_nickname-compatibility-mode -q -f nocrashdialog
-		winetricks prefix=$game_nickname-compatibility-mode -q -f d3dcompiler_43
-		winetricks prefix=$game_nickname-compatibility-mode -q -f d3dx9
+		#winetricks prefix=$game_nickname-compatibility-mode -q -f nocrashdialog
+		#winetricks prefix=$game_nickname-compatibility-mode -q -f d3dcompiler_43
+		#winetricks prefix=$game_nickname-compatibility-mode -q -f d3dx9
 
 		# Install d3dcompiler_47 dll
-		overrideDll() {
-			$CUSTOM_WINE_DIR/bin/wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
-		}
+		#overrideDll() {
+		#	$CUSTOM_WINE_DIR/bin/wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
+		#}
 
-		for dll in $(ls /opt/regataos-wine/dlls/default/x64/ | grep "dll"); do
-			cp -f "/opt/regataos-wine/dlls/default/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"
+		#for dll in $(ls /opt/regataos-wine/dlls/default/x64/ | grep "dll"); do
+		#	cp -f "/opt/regataos-wine/dlls/default/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"
 
-			overrideDll $(echo "$dll" | sed s/.dll//)
-		done
+		#	overrideDll $(echo "$dll" | sed s/.dll//)
+		#done
 
-		for dll in $(ls /opt/regataos-wine/dlls/default/x32/ | grep "dll"); do
-			cp -f "/opt/regataos-wine/dlls/default/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"
+		#for dll in $(ls /opt/regataos-wine/dlls/default/x32/ | grep "dll"); do
+		#	cp -f "/opt/regataos-wine/dlls/default/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"
 
-			overrideDll $(echo "$dll" | sed s/.dll//)
-		done
+		#	overrideDll $(echo "$dll" | sed s/.dll//)
+		#done
 
 		# Install DXVK and VKD3D-Proton dll's
 		#DXVK
@@ -94,7 +94,7 @@ function prepareCustomCompatMode() {
 			overrideDll $(echo "$dll" | sed s/.dll//)
 		done
 
-		echo -e "DXVK\nVKD3D-Proton" >> "$WINEPREFIX/vulkan.txt"
+		echo -e "DXVK\nVKD3D-Proton" >>"$WINEPREFIX/vulkan.txt"
 
 		# Check the winetricks cache present on the system.
 		if test ! -e "$HOME/.cache/winetricks/vcrun2019"; then
@@ -108,28 +108,28 @@ function prepareCustomCompatMode() {
 		sleep 5
 
 		rm -f $progressbar_dir/progress-movement
-		echo "completed" > $progressbar_dir/progress-full
-		echo "" > $progressbar_dir/status
-		echo $success_installation > $progressbar_dir/progress
+		echo "completed" >$progressbar_dir/progress-full
+		echo "" >$progressbar_dir/status
+		echo $success_installation >$progressbar_dir/progress
 		sleep 2
 		rm -f $progressbar_dir/*
 	fi
 }
 
 function prepareDefaultCompatMode() {
-	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode/drive_c"; then
 		# We're finished!
 		exit 0
 
-	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode" ; then
-		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode"; then
+		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
 			# Configuring compatibility mode
-			echo "installing" > $progressbar_dir/progress-movement
-			echo "" > $progressbar_dir/progress
-			echo $app_name > $progressbar_dir/app-name
-			echo $conf_prefix_status > $progressbar_dir/status
+			echo "installing" >$progressbar_dir/progress-movement
+			echo "" >$progressbar_dir/progress
+			echo $app_name >$progressbar_dir/app-name
+			echo $conf_prefix_status >$progressbar_dir/status
 			sleep 1
-			echo "show progress bar" > $progressbar_dir/progressbar
+			echo "show progress bar" >$progressbar_dir/progressbar
 
 			# Enable DXVK and VKD3D-Proton
 			if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
@@ -171,9 +171,9 @@ function prepareDefaultCompatMode() {
 			fi
 
 			rm -f $progressbar_dir/progress-movement
-			echo "completed" > $progressbar_dir/progress-full
-			echo "" > $progressbar_dir/status
-			echo $success_installation > $progressbar_dir/progress
+			echo "completed" >$progressbar_dir/progress-full
+			echo "" >$progressbar_dir/status
+			echo $success_installation >$progressbar_dir/progress
 			sleep 2
 			rm -f $progressbar_dir/*
 		else
@@ -181,17 +181,17 @@ function prepareDefaultCompatMode() {
 			exit 0
 		fi
 
-	elif test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
-		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	elif test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz"; then
+		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
 			# Configuring compatibility mode
-			echo "installing" > $progressbar_dir/progress-movement
-			echo "" > $progressbar_dir/progress
-			echo $app_name > $progressbar_dir/app-name
-			echo $conf_prefix_status > $progressbar_dir/status
+			echo "installing" >$progressbar_dir/progress-movement
+			echo "" >$progressbar_dir/progress
+			echo $app_name >$progressbar_dir/app-name
+			echo $conf_prefix_status >$progressbar_dir/status
 			sleep 1
-			echo "show progress bar" > $progressbar_dir/progressbar
+			echo "show progress bar" >$progressbar_dir/progressbar
 
-			if test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
+			if test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz"; then
 				tar xf "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" -C "$HOME/.local/share/wineprefixes/"
 			fi
 
@@ -235,9 +235,9 @@ function prepareDefaultCompatMode() {
 			fi
 
 			rm -f $progressbar_dir/progress-movement
-			echo "completed" > $progressbar_dir/progress-full
-			echo "" > $progressbar_dir/status
-			echo $success_installation > $progressbar_dir/progress
+			echo "completed" >$progressbar_dir/progress-full
+			echo "" >$progressbar_dir/status
+			echo $success_installation >$progressbar_dir/progress
 			sleep 2
 			rm -f $progressbar_dir/*
 		fi
@@ -247,12 +247,12 @@ function prepareDefaultCompatMode() {
 
 	else
 		# Configuring compatibility mode
-		echo "installing" > $progressbar_dir/progress-movement
-		echo "" > $progressbar_dir/progress
-		echo $app_name > $progressbar_dir/app-name
-		echo $conf_prefix_status > $progressbar_dir/status
+		echo "installing" >$progressbar_dir/progress-movement
+		echo "" >$progressbar_dir/progress
+		echo $app_name >$progressbar_dir/app-name
+		echo $conf_prefix_status >$progressbar_dir/status
 		sleep 1
-		echo "show progress bar" > $progressbar_dir/progressbar
+		echo "show progress bar" >$progressbar_dir/progressbar
 
 		/opt/regataos-gcs/scripts/prepare-default-compatibility-mode.sh start
 
@@ -296,20 +296,23 @@ function prepareDefaultCompatMode() {
 		fi
 
 		rm -f $progressbar_dir/progress-movement
-		echo "completed" > $progressbar_dir/progress-full
-		echo "" > $progressbar_dir/status
-		echo $success_installation > $progressbar_dir/progress
+		echo "completed" >$progressbar_dir/progress-full
+		echo "" >$progressbar_dir/status
+		echo $success_installation >$progressbar_dir/progress
 		sleep 2
 		rm -f $progressbar_dir/*
 	fi
 }
 
 case $1 in
-   "-dcm") prepareDefaultCompatMode
-         ;;
-   "-lcm") prepareCustomCompatMode
-         ;;
-   *) echo "Invalid option!"
-      exit 1
-      ;;
+"-dcm")
+	prepareDefaultCompatMode
+	;;
+"-lcm")
+	prepareCustomCompatMode
+	;;
+*)
+	echo "Invalid option!"
+	exit 1
+	;;
 esac
