Allow installation from the Epic Games Store without having to log into Game Access.

diff --git a/opt/regataos-gcs/scripts/install/en-us/install-game-gcs/prepare-compatibility-mode b/opt/regataos-gcs/scripts/install/en-us/install-game-gcs/prepare-compatibility-mode
--- a/opt/regataos-gcs/scripts/install/en-us/install-game-gcs/prepare-compatibility-mode
+++ b/opt/regataos-gcs/scripts/install/en-us/install-game-gcs/prepare-compatibility-mode
@@ -6,7 +6,7 @@
 game_nickname="$2"
 app_name="$(grep -r "gamename" /opt/regataos-gcs/games-list/$game_nickname.json | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g')"
 conf_prefix_status="Preparing compatibility mode..."
-success_installation="Concluded"
+success_installation="Concluded!"
 progressbar_dir="/tmp/progressbar-gcs"
 
 # If Vulkan is supported, enable DXVK and VKD3D-Proton
@@ -22,12 +22,12 @@ function prepareCustomCompatMode() {
 
 	else
 		# Configuring compatibility mode
-		echo "installing" > $progressbar_dir/progress-movement
-		echo "" > $progressbar_dir/progress
-		echo $app_name > $progressbar_dir/app-name
-		echo $conf_prefix_status > $progressbar_dir/status
+		echo "installing" >$progressbar_dir/progress-movement
+		echo "" >$progressbar_dir/progress
+		echo $app_name >$progressbar_dir/app-name
+		echo $conf_prefix_status >$progressbar_dir/status
 		sleep 1
-		echo "show progress bar" > $progressbar_dir/progressbar
+		echo "show progress bar" >$progressbar_dir/progressbar
 
 		export WINEDLLOVERRIDES="mscoree,mshtml="
 		export WINEPREFIX="$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
@@ -95,7 +95,7 @@ function prepareCustomCompatMode() {
 			overrideDll $(echo "$dll" | sed s/.dll//)
 		done
 
-		echo -e "DXVK\nVKD3D-Proton" >> "$WINEPREFIX/vulkan.txt"
+		echo -e "DXVK\nVKD3D-Proton" >>"$WINEPREFIX/vulkan.txt"
 
 		# Check the winetricks cache present on the system.
 		if test ! -e "$HOME/.cache/winetricks/vcrun2019"; then
@@ -109,28 +109,28 @@ function prepareCustomCompatMode() {
 		sleep 5
 
 		rm -f $progressbar_dir/progress-movement
-		echo "completed" > $progressbar_dir/progress-full
-		echo "" > $progressbar_dir/status
-		echo $success_installation > $progressbar_dir/progress
+		echo "completed" >$progressbar_dir/progress-full
+		echo "" >$progressbar_dir/status
+		echo $success_installation >$progressbar_dir/progress
 		sleep 2
 		rm -f $progressbar_dir/*
 	fi
 }
 
 function prepareDefaultCompatMode() {
-	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
 		# We're finished!
 		exit 0
 
-	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode" ; then
-		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode"; then
+		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
 			# Configuring compatibility mode
-			echo "installing" > $progressbar_dir/progress-movement
-			echo "" > $progressbar_dir/progress
-			echo $app_name > $progressbar_dir/app-name
-			echo $conf_prefix_status > $progressbar_dir/status
+			echo "installing" >$progressbar_dir/progress-movement
+			echo "" >$progressbar_dir/progress
+			echo $app_name >$progressbar_dir/app-name
+			echo $conf_prefix_status >$progressbar_dir/status
 			sleep 1
-			echo "show progress bar" > $progressbar_dir/progressbar
+			echo "show progress bar" >$progressbar_dir/progressbar
 
 			# Enable DXVK and VKD3D-Proton
 			if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
@@ -138,12 +138,12 @@ function prepareDefaultCompatMode() {
 			fi
 
 			cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
-			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
+				"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
 
 			rm -f $progressbar_dir/progress-movement
-			echo "completed" > $progressbar_dir/progress-full
-			echo "" > $progressbar_dir/status
-			echo $success_installation > $progressbar_dir/progress
+			echo "completed" >$progressbar_dir/progress-full
+			echo "" >$progressbar_dir/status
+			echo $success_installation >$progressbar_dir/progress
 			sleep 2
 			rm -f $progressbar_dir/*
 		else
@@ -151,17 +151,17 @@ function prepareDefaultCompatMode() {
 			exit 0
 		fi
 
-	elif test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
-		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
+	elif test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz"; then
+		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
 			# Configuring compatibility mode
-			echo "installing" > $progressbar_dir/progress-movement
-			echo "" > $progressbar_dir/progress
-			echo $app_name > $progressbar_dir/app-name
-			echo $conf_prefix_status > $progressbar_dir/status
+			echo "installing" >$progressbar_dir/progress-movement
+			echo "" >$progressbar_dir/progress
+			echo $app_name >$progressbar_dir/app-name
+			echo $conf_prefix_status >$progressbar_dir/status
 			sleep 1
-			echo "show progress bar" > $progressbar_dir/progressbar
+			echo "show progress bar" >$progressbar_dir/progressbar
 
-			if test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
+			if test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz"; then
 				tar xf "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" -C "$HOME/.local/share/wineprefixes/"
 			fi
 
@@ -171,12 +171,12 @@ function prepareDefaultCompatMode() {
 			fi
 
 			cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
-			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
+				"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
 
 			rm -f $progressbar_dir/progress-movement
-			echo "completed" > $progressbar_dir/progress-full
-			echo "" > $progressbar_dir/status
-			echo $success_installation > $progressbar_dir/progress
+			echo "completed" >$progressbar_dir/progress-full
+			echo "" >$progressbar_dir/status
+			echo $success_installation >$progressbar_dir/progress
 			sleep 2
 			rm -f $progressbar_dir/*
 		fi
@@ -186,12 +186,12 @@ function prepareDefaultCompatMode() {
 
 	else
 		# Configuring compatibility mode
-		echo "installing" > $progressbar_dir/progress-movement
-		echo "" > $progressbar_dir/progress
-		echo $app_name > $progressbar_dir/app-name
-		echo $conf_prefix_status > $progressbar_dir/status
+		echo "installing" >$progressbar_dir/progress-movement
+		echo "" >$progressbar_dir/progress
+		echo $app_name >$progressbar_dir/app-name
+		echo $conf_prefix_status >$progressbar_dir/status
 		sleep 1
-		echo "show progress bar" > $progressbar_dir/progressbar
+		echo "show progress bar" >$progressbar_dir/progressbar
 
 		/opt/regataos-gcs/scripts/prepare-default-compatibility-mode.sh start
 
@@ -201,23 +201,26 @@ function prepareDefaultCompatMode() {
 		fi
 
 		cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
-		"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
+			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
 
 		rm -f $progressbar_dir/progress-movement
-		echo "completed" > $progressbar_dir/progress-full
-		echo "" > $progressbar_dir/status
-		echo $success_installation > $progressbar_dir/progress
+		echo "completed" >$progressbar_dir/progress-full
+		echo "" >$progressbar_dir/status
+		echo $success_installation >$progressbar_dir/progress
 		sleep 2
 		rm -f $progressbar_dir/*
 	fi
 }
 
 case $1 in
-   "-dcm") prepareDefaultCompatMode
-         ;;
-   "-lcm") prepareCustomCompatMode
-         ;;
-   *) echo "Invalid option!"
-      exit 1
-      ;;
+"-dcm")
+	prepareDefaultCompatMode
+	;;
+"-lcm")
+	prepareCustomCompatMode
+	;;
+*)
+	echo "Invalid option!"
+	exit 1
+	;;
 esac
